0.1.0a
Cleaned up code.
Problem: In World.cs all the lines
"foreach(Chunk c in this._LoadedChunks)"
are causing >
InvalidOperationException: Collection was modified; enumeration
operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException
(System.ExceptionResource resource) [0x0000b] in
<ac823e2bb42b41bda67924a45a0173c3>:0
at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare ()
[0x00013] in <ac823e2bb42b41bda67924a45a0173c3>:0
at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a]
in <ac823e2bb42b41bda67924a45a0173c3>:0
at World.<Start>b__11_0 () [0x00258] in C:\Users\Public\Documents\Unity
Projects\Hephaestus\Assets\Scripts\World.cs:75

UnityEngine.Debug:Log(Object)
World:<Start>b__11_0() (at
Assets/Scripts/World.cs:122)
System.Threading.ThreadHelper:ThreadStart()